// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/pymodel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PredictService_Predict_FullMethodName = "/proto.PredictService/Predict"
)

// PredictServiceClient is the client API for PredictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PredictServiceClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
}

type predictServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPredictServiceClient(cc grpc.ClientConnInterface) PredictServiceClient {
	return &predictServiceClient{cc}
}

func (c *predictServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, PredictService_Predict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictServiceServer is the server API for PredictService service.
// All implementations must embed UnimplementedPredictServiceServer
// for forward compatibility
type PredictServiceServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	mustEmbedUnimplementedPredictServiceServer()
}

// UnimplementedPredictServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPredictServiceServer struct {
}

func (UnimplementedPredictServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedPredictServiceServer) mustEmbedUnimplementedPredictServiceServer() {}

// UnsafePredictServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PredictServiceServer will
// result in compilation errors.
type UnsafePredictServiceServer interface {
	mustEmbedUnimplementedPredictServiceServer()
}

func RegisterPredictServiceServer(s grpc.ServiceRegistrar, srv PredictServiceServer) {
	s.RegisterService(&PredictService_ServiceDesc, srv)
}

func _PredictService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PredictService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServiceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PredictService_ServiceDesc is the grpc.ServiceDesc for PredictService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PredictService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PredictService",
	HandlerType: (*PredictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _PredictService_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pymodel.proto",
}
