# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pymodel.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/pymodel.proto\x12\x05proto\":\n\x08\x46\x65\x61tures\x12\x0e\n\x02id\x18\x01 \x01(\x05R\x02id\x12\x0e\n\x02\x66\x31\x18\x02 \x01(\x01R\x02\x66\x31\x12\x0e\n\x02\x66\x32\x18\x03 \x01(\x01R\x02\x66\x32\"<\n\nPrediction\x12\x0e\n\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n\nprediction\x18\x02 \x01(\x01R\nprediction\"=\n\x0ePredictRequest\x12+\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x0f.proto.FeaturesR\x08\x66\x65\x61tures\"F\n\x0fPredictResponse\x12\x33\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x11.proto.PredictionR\x0bpredictions2L\n\x0ePredictService\x12:\n\x07Predict\x12\x15.proto.PredictRequest\x1a\x16.proto.PredictResponse\"\x00\x42$Z\"github.com/matoravec/pymodel/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pymodel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/matoravec/pymodel/proto'
  _globals['_FEATURES']._serialized_start=30
  _globals['_FEATURES']._serialized_end=88
  _globals['_PREDICTION']._serialized_start=90
  _globals['_PREDICTION']._serialized_end=150
  _globals['_PREDICTREQUEST']._serialized_start=152
  _globals['_PREDICTREQUEST']._serialized_end=213
  _globals['_PREDICTRESPONSE']._serialized_start=215
  _globals['_PREDICTRESPONSE']._serialized_end=285
  _globals['_PREDICTSERVICE']._serialized_start=287
  _globals['_PREDICTSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
